# fly.toml app configuration file generated for zirkel-api on 2025-04-24T11:32:28-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zirkel-api'
primary_region = 'gdl'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3000'
  IMAGES_PATH='/data/media_images'
  GOOGLE_SLIDES_PROPOSAL_TEMPLATE='1jH_0q4_5j1zHUVxeVOwuwxFWqR6twv-JNmFYUifE4wE'
  GOOGLE_DRIVE_PROPOSAL_FOLDER='19SuCK9XwnEuYai8-I9L1zPFk3aCef4dW'
  NEXT_PUBLIC_API_BASE_URL='http://localhost:3002'

[http_service]
  internal_port = 3000
  force_https = true
  processes = ['app']
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '3gb'
  cpu_kind = 'shared'
  cpus = 2

[mounts]
  source = "zirkel_data"
  destination = "/data"

[[volumes]]
  name = "zirkel_data"
  size = "1"
